#!/bin/bash

source /etc/profile.d/z00_lmod.sh
module load gcc/8.1.0
#module load gcc/7.1.0
#module load cmake/3.9.2

set -x

installdir=`pwd`/install

mkdir install

mkdir deps
cd deps

depsdir=`pwd`


if [ ! -d KVTree ] ; then
  git clone git@github.com:ECP-Veloc/KVTree.git KVTree
fi

rm -rf KVTree/build
mkdir KVTree/build

cd KVTree/build
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-O0" -DCMAKE_INSTALL_PREFIX=$installdir -DMPI=ON ..
make clean
make
make install
cd $depsdir

