name: axl build

permissions:
  actions: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        target: [Debug, Release]
        mpi: [seq, par]
        shared: [true, false]
        static: [true, false]

    name: ${{ matrix.os }}-${{ matrix.target }}-${{ matrix.mpi }}-${{ matrix.shared }}-${{ matrix.static }}

    runs-on: ${{ matrix.os }}

    steps:

      - name: checkout
        uses: actions/checkout@v3
        with:
          path: axl
          fetch-depth: 0

      - name: get deps
        uses: ecp-veloc/github-actions/get-scr-os-deps@main
        with:
          os: ${{ matrix.os }}
          mpi: ${{ matrix.mpi }}

      - name: build kvtree
        uses: ecp-veloc/github-actions/build-ecp-veloc-component@main
        with:
          component: kvtree
          mpi: ${{ matrix.mpi }}
          shared: ${{ matrix.shared }}

      - name: build static
        uses: ecp-veloc/github-actions/cmake-build-static@main
        with:
          component: axl
          target: ${{ matrix.target }}
          shared: ${{ matrix.shared }}
          cmake_line: "-DMPI=${{ matrix.mpi == 'par' }}"

      - name: build only
        uses: ecp-veloc/github-actions/cmake-build-only@main
        with:
          component: axl
          target: ${{ matrix.target }}
          shared: ${{ matrix.shared }}
          static: ${{ matrix.static }}
          cmake_line: "-DMPI=${{ matrix.mpi == 'par' }}"
